[package]
name = "evm"
version = "0.1.0"
edition = "2021"
[dependencies]
primitive-types = "0.12.1"
sha3 = "0.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

